version: '3'
services:

  frontend:
    restart: always
    image: stormer1911/frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - backend
      - postgres
    ports:
      - 80:80
    stdin_open: true